[project]
name = "mulch-troop-589"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "folium>=0.19.5",
    "geopy>=2.4.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "shapely>=2.1.0",
]
